services:
  mongo:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  node-app:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo: